apiVersion: v1
kind: Pod
metadata:
  labels:
  name: myapp
spec:
  containers:
  - image: redis
    name: redis
  - image: nginx
    name: nginx
  - image: memcached
    name: memcached
  - image: consul  
    name: consul
    
    
COmmands: vim myapp.yaml
kubectl apply -f myapp.yaml
kubectl get pods
