apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: redispod
  name: redispod
  namespace: web
spec:
  containers:
  - image: redis
    name: redispod
    ports:
    - containerPort: 9090
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
contexts:      


commands:
kubectl run --generator=run-pod/v1 redispod --image=redis --port=9090 --namespace=web  --dry-run -o yaml > redisPOD.yaml
added namespace: web in vim
kubectl apply -f redisPOD.yaml
